### ISSUE TITLE
Strange behavior with special numbered: named workspaces

### ISSUE THREAD

**Issue by ViktorNova** [lynks--/lifebar#11]
This is hard to explain with text, so here is a screenshot.
Lifebar doesn't seem to like having : colons in the workspace name. My workspaces are numbered like

```
1: Session
2: Patchbay
```

etc, but when I click on them in lifebar, it creates an extra workspace with the colon stripped out, so I end up having something like this:

```
1: Session
2: Patchbay
2 Patchbay
```

as displayed in i3bar, and lifebar doesn't show the colons at all

Here's a screenshot with i3bar on top and lifebar on the bottom (this behavior only happens when the workspace is clicked on in lifebar, not when switched to with key commands or clicked in i3bar)
![image](https://f.cloud.github.com/assets/3234333/2418546/01864d2c-ab46-11e3-8168-9e619182b266.png)

**Comment by msx** [comment]
Hello,
How can I rename the workspaces in lifebar?

**Comment by lynks--** [comment]
Lifebar just takes the names you use in i3 and displays them. In your i3 config you will find some lines that look like:

`bindsym Mod1+1 workspace 1`

Which means: `when I press Alt+1, switch to workspace "1"`

"1" is actually the workspace name.

You can see this by interacting with i3 using `i3-msg`, open a terminal and try the following:

`i3-msg workspace foo`

**Comment by msx** [comment]
That was fast, TY :)
