### ISSUE TITLE
[ Question ] Tray area for icons

### ISSUE THREAD

**Issue by msx** [lynks--/lifebar#21]
Hi,
Do you plan to add a system tray bar to lifebar (I don't know if that's even possible)?
For now I'm using a customized tint2 but well, it would be great to have everything together in the same place.

**Comment by lynks--** [comment]
Yep that's possible, and it's something I would like to add in the future. It hasn't been a priority for me as I don't believe I use any apps that add a tray icon! I can't give an estimate on when I'll get around to it, but as you've asked, I'll look into how it's done.

**Comment by msx** [comment]
Wee! Many thanks.
