### ISSUE TITLE
screenshot is gone :(

### ISSUE THREAD

**Issue by RasmusWL** [lynks--/lifebar#23]

**Comment by msx** [comment]
Here you have: http://i.imgur.com/BkWbDp5.png
(The first line is tmux)

**Comment by RasmusWL** [comment]
Great! Could you update the README as well ?

**Comment by msx** [comment]
I'm afraid that, my friend, it's up to lynks--.
However in the event he agrees I have no problem in cloning the repo and commiting a new README.md file with a screenshot :)

**Comment by RasmusWL** [comment]
Oh, I see. my bad. Thanks for providing the screenshot though :)

**Comment by lynks--** [comment]
Updated :)
